var transcriptData = [
  // Video 1
  // -------
  [ 
    { time: 0.2, text: "Now that we've looked at the architecture of the internet, let's see how you might"},
    { time: 4.1, text: "connect your personal devices to the internet inside your house."},
    { time: 7.5, text: "Well there are many ways to connect to the internet, and"},
    { time: 11.2, text: "most often people connect wirelessly."},
    { time: 13.9, text: "Let's look at an example of how you can connect to the internet."},
    { time: 17.9, text: "If you live in a city or a town, you probably have a coaxial cable for"},
    { time: 22.3, text: "cable Internet, or a phone line if you have DSL, running to the outside of"},
    { time: 26.8, text: "your house, that connects you to the Internet Service Provider, or ISP."},
    { time: 32.1, text: "If you live far out in the country, you'll more likely have"},
    { time: 34.7, text: "a dish outside your house, connecting you wirelessly to your closest ISP, or"},
    { time: 39.4, text: "you might also use the telephone system."},
    { time: 42.3, text: "Whether a wire comes straight from the ISP hookup outside your house, or"},
    { time: 46.3, text: "it travels over radio waves from your roof,"},
    { time: 49.2, text: "the first stop a wire will make once inside your house, is at your modem."},
    { time: 53.7, text: "A modem is what connects the internet to your network at home."},
    { time: 57.7, text: "A few common residential modems are DSL or"},
  ],
  // Video 2
  // -------
  [
    { time: 0.4, text: "[MUSIC]"},
    { time: 5.0, text: "[SOUND] Does writing plain JavaScript scare you, or"},
    { time: 7.8, text: "do you simply want to get a better grasp of JavaScript?"},
    { time: 10.9, text: "Then this is the course for you."},
    { time: 13.0, text: "We're going to use JavaScript to create a to-do list application without any"},
    { time: 17.1, text: "third-party libraries like jQuery."},
    { time: 19.7, text: "I'm Andrew, a JavaScript developer and"},
    { time: 21.6, text: "your guide to getting skilled up writing pure JavaScript code."},
    { time: 25.4, text: "JavaScript is becoming a general purpose language, and it's used on"},
    { time: 28.8, text: "the server side with Node js, in electronics with devices like the Tessel,"},
    { time: 33.0, text: "and in crossplatform smartphone app SDKs like Titanium."},
    { time: 37.7, text: "Browser based libraries, like jQuery, do a lot of the heavy lifting for"},
    { time: 41.1, text: "common tasks in a cross browser compatible way."},
    { time: 44.8, text: "However, its ease of use can leave people feeling"},
    { time: 48.2, text: "uncomfortable writing JavaScript alone."},
    { time: 51.6, text: "We're going to do a handful of common tasks that you could do easily with"},
    { time: 55.7, text: "jQuery but are just as nearly as easy to write in pure JavaScript."},
    { time: 60.9, text: "The aim of this course is to get you more confident in your abilities writing"},
    { time: 64.9, text: "JavaScript code first in it's home in the browser, so you can go out and"},
    { time: 69.7, text: "explore more possibilities."},
    { time: 72.3, text: "If you're new to JavaScript,"},
    { time: 73.9, text: "you may want to checkout some of the other JavaScript courses first."},
    { time: 78.0, text: "They'll be linked in the teacher notes."},
  ],
  // Video 3
  // -------
  [
    { time: 0, text: "[MUSIC]"},
    { time: 4.2, text: "[SOUND] Text and images have always been the foundation of web content, but"},
    { time: 9.2, text: "more than ever, video and audio are also a part of that content mix."},
    { time: 13.7, text: "In this project, we'll learn how to use the HTML video and"},
    { time: 17.4, text: "audio elements to playback media."},
    { time: 20.2, text: "We'll also learn how to add features like, captioning and custom playback controls."},
    { time: 25.9, text: "First, let's take a look at the project."},
    { time: 28.9, text: "It's actually pretty simple."},
    { time: 30.2, text: "It's just a video player on a web page along with an audio player."},
    { time: 35.3, text: "This may not look very impressive, but if you've been working in web technology for"},
    { time: 39.7, text: "even just a few years, you probably know how long it took for"},
    { time: 43.3, text: "web technology to catch up with video."},
    { time: 46.2, text: "Video on the web used to involve plugins like QuickTime, Flash, RealPlayer, and"},
    { time: 51.0, text: "several others."},
    { time: 52.4, text: "However, using browser plug-ins is typically bad for"},
    { time: 56.2, text: "accessibility, mobile devices, battery life, and many other factors."},
    { time: 60.8, text: "If you can avoid browser plugins, you should, fortunately, we can create"},
    { time: 66.1, text: "standards based video and audio players that don't require the use of plugins."},
    { time: 71.7, text: "Adding video and"},
    { time: 72.5, text: "audio to a webpage is almost as easy as adding an image or formatting some text."},
    { time: 78.1, text: "In this course, we're going to spend most of our time focusing on just two elements,"},
    { time: 83.0, text: "the video element and the audio element."},
    { time: 86.3, text: "We'll learn about a few others, but those two are the most important."},
    { time: 90.2, text: "Now, let's move on and give the video element a try."},
  ],
  // Video 4
  // -------
  [
    { time: 0, text: "[MUSIC]"},
    { time: 4.8, text: "I've shown you how to use constructives, prototypes and object laterals."},
    { time: 9.3, text: "In this project we're going to make use of all of these concepts."},
    { time: 12.8, text: "We're going to create a quiz application."},
    { time: 14.7, text: "The quiz will ask a series of questions, and as we answer the questions,"},
    { time: 18.4, text: "the quiz will keep record of our score."},
    { time: 21.0, text: "When the questions are all asked, the application will display our score."},
    { time: 26.8, text: "You're going to be tasked with creating the JavaScript programming for"},
    { time: 29.5, text: "this application."},
    { time: 30.6, text: "I've already got the HTML ready for you."},
    { time: 33.2, text: "Let's take a quick look at the application in the workspace"},
    { time: 35.8, text: "associated with this video."},
    { time: 38.0, text: "Here we have an HTML file with a H2 tag with the ID of question."},
    { time: 44.9, text: "This is where we can put the question."},
    { time: 48.5, text: "We have two choice paragraphs with the IDs of choice zero and"},
    { time: 55.4, text: "choice one And we have two select answer buttons."},
    { time: 62.9, text: "With guess zero and guess one."},
    { time: 66.7, text: "At the bottom here, we have a paragraph with the ID of progress."},
    { time: 72.0, text: "This is to indicate to the user how far we are through the quiz."},
    { time: 76.3, text: "I've created some JavaScript files to give you hints on the direction you need to go."},
    { time: 83.4, text: "You'll need the quiz itself, which will keep track of the score and"},
    { time: 87.3, text: "the current question, kind of like what the playlist was."},
    { time: 90.9, text: "A playlist is a collection of songs."},
    { time: 92.7, text: "A quiz is a collection of questions."},
    { time: 96.7, text: "You'll also need something to handle all the updates to the UI."},
    { time: 100.6, text: "And finally, you need an app.js file to start the application with all the objects"},
    { time: 105.0, text: "that you've created."},
    { time: 106.9, text: "Look up the previous projects you worked on to give you inspiration."},
    { time: 110.6, text: "You can even copy and paste some of the code to use as a starting point for"},
    { time: 114.5, text: "your objects."},
    { time: 115.5, text: "It's not cheating."},
    { time: 116.7, text: "In fact understanding existing code and then applying that"},
    { time: 120.1, text: "code into another program is an important skill for any JavaScript developer."},
    { time: 125.2, text: "Remember the tools at your disposal."},
    { time: 127.5, text: "You can use get element by ID to get the HTML elements, but"},
    { time: 131.1, text: "you need to update with inner HTML."},
    { time: 134.0, text: "You can assign methods to the onClick of various elements like the buttons."},
    { time: 138.5, text: "You've also got the ability to use constructors, prototypes and"},
    { time: 141.7, text: "object literals."},
    { time: 143.4, text: "Take some time to plot out the objects, properties and methods you'll need."},
    { time: 147.9, text: "In the following videos, I'll show you my solution."},
    { time: 150.3, text: "Give it a try and come back to me and see how I did it."},
  ],
  // Video 5
  // -------
  [
    { time: 0, text: "This is gonna take forever, to be continued." }
  ],
  // Video 6
  // -------
  [
    { time: 0, text: "This is gonna take forever, to be continued." }
  ]
];